name: Aerospike Go Client Tests
'on':
  push:
  pull_request:

env:
  AEROSPIKE_HOSTS: '127.0.0.1:3000'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - '1.16'
          - '1.17'
          - '1.18'
          - '1.19'
    steps:
      - uses: actions/checkout@v3
      - name: 'Setup Go ${{ matrix.go-version }}'
        uses: actions/setup-go@v3
        with:
          go-version: '${{ matrix.go-version }}'
          #cache: true
      - name: Display Go version
        run: go version
      - name: Set up Aerospike Database
        uses: reugn/github-action-aerospike@v1
      - name: Install Ginkgo
        run: GO111MODULE="auto" go get github.com/onsi/ginkgo/ginkgo
      - name: Install Gomega
        run: GO111MODULE="auto" go get github.com/onsi/gomega
#      - name: Install Dependencies
#        run: GO111MODULE="auto" go get .
      - name: Test Lua Code
        run: GO111MODULE="auto" ginkgo -cover -race -r -keepGoing -succinct -randomizeSuites internal/lua
      - name: Test types package
        run: GO111MODULE="auto" ginkgo -cover -race -r -keepGoing -succinct -randomizeSuites types
      - name: Test pkg tests
        run: GO111MODULE="auto" ginkgo -cover -race -r -keepGoing -succinct -randomizeSuites pkg
      - name: Build Benchmark tool
        run: cd tools/benchmark | go build -o benchmark .
      - name: Build asinfo tool
        run: cd tools/asinfo | go build -o asinfo .
      - name: Build cli tool
        run: cd tools/cli | go build -o cli .
      - name: Build example files
        run: find examples -name "*.go" -type f -print0 | xargs -0 -n1 go build
      - name: Build with Reflection code removed
        run: GO111MODULE="auto" ginkgo build -tags="as_performance" .
      - name: Build for Google App Engine (unsafe package removed)
        run: GO111MODULE="auto" ginkgo build -tags="app_engine" .
      - name: Run the tests
        run: GO111MODULE="auto" ginkgo -race -keepGoing -succinct -randomizeSuites -slowSpecThreshold=15
